import type { NextPage } from "next";
import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import { WalletContext } from "components/context/walletContext";
import Link from "next/link";
import { useRouter } from "next/router";
import AlertContext from "components/context/alertContext";

const Home: NextPage = () => {
  const walletContext = useContext(WalletContext);
  const [walletStatus, setWalletStatus] = useState(false);
  const router = useRouter();
  const alert = useContext(AlertContext);

  const ConnectWallet = () => {
    walletContext.myAlgoConnect
      .connect()
      .then((accounts) => {
        walletContext.setAccounts(accounts);
        localStorage.setItem("accounts.name", accounts[0].name);
        localStorage.setItem("accounts.address", accounts[0].address);
        var timeObject = { value: "value", timestamp: new Date().getTime() };
        localStorage.setItem("accounts.timestamp", JSON.stringify(timeObject));
        router.push("/all");
      })
      .catch(alert.error);
  };

  useEffect(() => {
    if (walletContext.accounts.length === 0) return;
    if (walletContext.accounts[0].expired) return;
    setWalletStatus(true);
  }, [walletContext]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex items-center justify-center h-screen">
          <div className="p-10">
            <h1 className="font-sans font-bold text-7xl p-7">
              Algorand NFT Toolbox
            </h1>
            <div className="flex items-center justify-center">
              {walletStatus ? (
                <Link href="/all">
                  <button
                    type="button"
                    className="py-2 px-4 bg-gradient-to-r from-blue-400 to-blue-800 text-white  transition ease-in duration-200 text-center text-base font-semibold shadow-md rounded-lg"
                  >
                    Connect Wallet
                  </button>
                </Link>
              ) : (
                <button
                  onClick={ConnectWallet}
                  type="button"
                  className="py-2 px-4 bg-gradient-to-r from-blue-400 to-blue-800 text-white  transition ease-in duration-200 text-center text-base font-semibold shadow-md rounded-lg"
                >
                  Connect Wallet
                </button>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
